### PR TITLE
Add secret_key as request option

### PR DESCRIPTION
**Pull request by dougmartin**
Adds secret_key as a request option so that you can dynamically switch between test and live mode.

### CODE REVIEW

**Comment by dougmartin** [comment]
The diff is a little busy as my editor automatically removes trailing spaces on lines.

**Comment by sikanhe** [comment]
@dougmartin Thanks for doing the PR. Do you mind adding some unit tests for this feature? Also when i get time i will be doing a rewrite for this library to let users explicitly call`Stripe.doSomething() |> Stripe.request(opts)` where Stripe.request() will take request options including passing a custom key. Let me know what you think of that

**Comment by dougmartin** [comment]
Sure - sorry I should have added some tests.

**Comment by dougmartin** [comment]
Closing during cleanup of old non-merged PRs.

**Pull request closed without merging**
